services:
  - type: web
    name: whatsapp-bday-bot
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: ADMIN_PASSWORD
        generateValue: true
      - key: FILEBASE_KEY
        value: 6014403412011DDBA685
      - key: FILEBASE_SECRET
        value: 7EcuQ8Ffwqbg4Ge69gE6AywuwwtoIXP0H9U7mCP0
      - key: FILEBASE_BUCKET
        value: session1
      - key: FILEBASE_ENDPOINT
        value: https://s3.filebase.io
      - key: FILEBASE_REGION
        value: us-east-1
